export const USSD_CODES: Record<string, string> = {
  GTB: "*737*2*AMOUNT*ACCOUNT#",
  FirstBank: "*894*AMOUNT*ACCOUNT#",
  Access: "*901*2*AMOUNT*ACCOUNT#",
  Ecobank: "*326*AMOUNT*ACCOUNT#",
  FCMB: "*329*AMOUNT*ACCOUNT#",
  Fidelity: "*770*AMOUNT*ACCOUNT#",
  Polaris: "*833*AMOUNT*ACCOUNT#",
  Sterling: "*822*5*AMOUNT*ACCOUNT#",
  UBA: "*919*4*ACCOUNT*AMOUNT#",
  UnionBank: "*826*2*AMOUNT*ACCOUNT#",
  Zenith: "*966*AMOUNT*ACCOUNT#",
  StanbicIBTC: "*909*22*AMOUNT*ACCOUNT#",
  Heritage: "*322*030*ACCOUNT*AMOUNT#",
  Keystone: "*7111*AMOUNT*ACCOUNT#",
  "Wema (ALAT)": "*945*ACCOUNT*AMOUNT#",
  Unity: "*7799*2*ACCOUNT*AMOUNT#",
  Providus: "*730*AMOUNT*ACCOUNT#",
  StandardChartered: "*977*AMOUNT*ACCOUNT#",
  TitanTrust: "*922*AMOUNT*ACCOUNT#",
  Globus: "*989*AMOUNT*ACCOUNT#",
  LotusBank: "*5045*AMOUNT*ACCOUNT#",
  SunTrust: "*5230*AMOUNT*ACCOUNT#",
  NovaMerchant: "*545*AMOUNT*ACCOUNT#",
  PolarisBank: "*833*AMOUNT*ACCOUNT#",
  JaizBank: "*773*AMOUNT*ACCOUNT#",
  FCMB_MFB_variant: "*329*AMOUNT*ACCOUNT#",
  KeystoneBank: "*7111*AMOUNT*ACCOUNT#",
  Moniepoint: "*5573*2*AMOUNT*ACCOUNT#",
  Paga: "*242*AMOUNT*ACCOUNT#",
  Carbon: "*1303*4*AMOUNT*ACCOUNT#.",
  Moniepoint_MFB: "*5573*2*AMOUNT*ACCOUNT#",
  BlocMFB: "55732*AMOUNT*ACCOUNT#",
  AccionMFB: "*572*2*AMOUNT*ACCOUNT#",
  RubiesMFB: "*7797*2*AMOUNT*ACCOUNT#",
  PagaWallet: "*242*AMOUNT*ACCOUNT#",
  MoniepointAgent: "*5573*2*AMOUNT*ACCOUNT#",
  Opay: "USSD_AVAILABLE (e.g. *955#) — inter-bank transfer VIA USSD reported in some sources as menu flow (confirm exact template with Opay).",
  PalmPay:
  "USSD_AVAILABLE (e.g. *652# or *861#) — uses menu-driven USSD; no single universal *AMOUNT*ACCOUNT# template publically confirmed for interbank (confirm with PalmPay).",
  Kuda: "NO_USSD_TRANSFER (app-only; Kuda Microfinance Bank uses app flows; check Kuda docs).",
  ChaseMFB:
  "MENU/COMPOSITE USSD (often uses bank code+0226 pattern) — VERIFY_WITH_BANK",
  FairMoney:
  "USSD funding supported (app-focused); interbank USSD template not standardized publicly — VERIFY_WITH_BANK.",
  RenMoney: "NO_PUBLIC_USSxxxxxxxxxxxxxxxxxxxxxxxxxxxxxD_TRANSFER_TEMPLATE — VERIFY_WITH_PROVIDER",
  FairMoneyBankAccount:
    "BANK_ACCOUNT_FUNDING via bank transfer or USSD topup (VERIFY exact template)",
  "Paycom/OpayAgent":
    "*955# (menu-driven). Confirm transfer template with Opay.",
};
